-- Baseball Dugout: Load Data from Stage
-- Run after uploading CSV files to BASEBALL_DATA_STAGE

USE DATABASE BASEBALL_ANALYTICS;
USE SCHEMA PLAYER_DATA;
USE WAREHOUSE BASEBALL_WAREHOUSE;

-- Load Master (players)
COPY INTO MASTER FROM @BASEBALL_DATA_STAGE/Master.csv
ON_ERROR = 'CONTINUE';

-- Load Batting
COPY INTO BATTING FROM @BASEBALL_DATA_STAGE/Batting.csv
ON_ERROR = 'CONTINUE';

-- Load Pitching
COPY INTO PITCHING FROM @BASEBALL_DATA_STAGE/Pitching.csv
ON_ERROR = 'CONTINUE';

-- Load Teams
COPY INTO TEAMS FROM @BASEBALL_DATA_STAGE/Teams.csv
ON_ERROR = 'CONTINUE';

-- Load Hall of Fame
COPY INTO HALLOFFAME FROM @BASEBALL_DATA_STAGE/HallOfFame.csv
ON_ERROR = 'CONTINUE';

-- Load All-Star appearances
COPY INTO ALLSTARFULL FROM @BASEBALL_DATA_STAGE/AllstarFull.csv
ON_ERROR = 'CONTINUE';

-- Load Salaries
COPY INTO SALARIES FROM @BASEBALL_DATA_STAGE/Salaries.csv
ON_ERROR = 'CONTINUE';

-- Load Teams Franchises
COPY INTO TEAMS_FRANCHISES FROM @BASEBALL_DATA_STAGE/TeamsFranchises.csv
ON_ERROR = 'CONTINUE';

-- Verify row counts
SELECT 'master' AS table_name, COUNT(*) AS row_count FROM MASTER
UNION ALL SELECT 'batting', COUNT(*) FROM BATTING
UNION ALL SELECT 'pitching', COUNT(*) FROM PITCHING
UNION ALL SELECT 'teams', COUNT(*) FROM TEAMS
UNION ALL SELECT 'halloffame', COUNT(*) FROM HALLOFFAME
UNION ALL SELECT 'allstarfull', COUNT(*) FROM ALLSTARFULL
UNION ALL SELECT 'salaries', COUNT(*) FROM SALARIES
UNION ALL SELECT 'teams_franchises', COUNT(*) FROM TEAMS_FRANCHISES
ORDER BY table_name;

